### ISSUE TITLE
AGL Live about Communicart with Raphy and John Felleman

### ISSUE THREAD

**Issue by RobertLRead** [agilegovleaders/agile-champions#18]
Raphy Villas and John Felleman have created "Communicart", an important project in government.  I think this is worth an AGL interview.

**Comment by phirefly** [comment]
Per our convo. I will reach out to John and follow-up.

**Comment by melindaburgess** [comment]
- [ ] Confirm participants
- [ ] Determine date
- [ ] Create panelist guide with date/time, topics, talking points, and panelist info
- [ ] Create Hangout On Air, Eventbrite, and new event on AGL site 
- [ ] Promote via AGL blog and social media prior to show
- [ ] Arrange pre-show meeting with all participants
- [ ] AGL Live
- [ ] Promote video via AGL blog and social media post-show
- [ ] Adjust YouTube video settings
- [ ] Send thank-you and video link to participants, suggest they re-post to social media
