### ISSUE TITLE
Items to add to Handbook

### ISSUE THREAD

**Issue by melindaburgess** [agilegovleaders/agile-champions#26]
Comment on this card to suggest items that could be added to the Agile Gov Handbook.

GOOD THINGS FOR HANDBOOK:
- Is the content easily digested in a couple of minutes? 
- Does the content lead the reader quickly to an understanding of a concept of agile gov?
- Does the content highlight an important document, initiative, requirement, or practice?
- Does the content help the reader understand current agile gov best practices at a glance? 

THINGS TO AVOID IN HANDBOOK:
- Does the content dive deeply into nuances or specific practices?
- Does the content take longer than 3 minutes to read / watch / digest?
- Is the content outdated?
- Is there a better version of similar content / concepts?

**Comment by RobertLRead** [comment]
You could add to the "Articles" section the article that Henry and I wrote about Agile procurement Challenges publichsed at Hacker Noon on Medium: https://hackernoon.com/guidelines-for-agile-challenge-based-procurement-4531ff335422#.qhw5w4tzd

**Comment by melindaburgess** [comment]
TechFar Hub 
https://techfarhub.cio.gov/
The TechFAR Hub provides resources to apply industry best practices to the world of digital service acquisition across the federal government (including advice for agile acquisition)

**Comment by plotboy** [comment]
Topics section
I recommend that we add the topics as expandable links so that we can choose which topic we want to see instead of scrolling through the entire list

**Comment by plotboy** [comment]
Benefits
I'd like to draft a paragraph of describing the benefits of Agile in gov - then go into the TechFAR and other examples.
